In [3]:
import numpy as np 
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder
from sklearn.svm import SVC, SVR
from sklearn.metrics import precision_score, recall_score, f1_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.preprocessing import PolynomialFeatures

In [4]:
columns = ['age','workClass','fnlwgt','education','education-num','marital-status',
 'occupation','relationship','race','sex','capital-gain','capital-loss',
 'hours-per-week','native-country','income']
data = pd.read_csv("adultdata.csv", names=columns)
data.head()

age          workClass  fnlwgt   education  education-num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   
3   53            Private  234721        11th              7   
4   28            Private  338409   Bachelors             13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital-gain  capital-loss  hours-per-week  native-country  income  
0          2174             0              40   United-States   <=50K  
1             0             0              13   United-States   <=50K  
2             0             0              40   United-States   <=50K  
3             0             0              40   United-States   <=50K  
4             0             0              40            Cuba   <=50K

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
age               32561 non-null int64
workClass         32561 non-null object
fnlwgt            32561 non-null int64
education         32561 non-null object
education-num     32561 non-null int64
marital-status    32561 non-null object
occupation        32561 non-null object
relationship      32561 non-null object
race              32561 non-null object
sex               32561 non-null object
capital-gain      32561 non-null int64
capital-loss      32561 non-null int64
hours-per-week    32561 non-null int64
native-country    32561 non-null object
income            32561 non-null object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB


In [6]:
workClassle = LabelEncoder()
workClassint = workClassle.fit_transform(data.workClass)

In [7]:
workClassint 

array([7, 6, 4, ..., 4, 4, 5])

In [8]:
educationle = LabelEncoder()
educationint = educationle.fit_transform(data.education)

In [9]:
educationint

array([ 9,  9, 11, ..., 11, 11, 11])

In [10]:
marital_statusle = LabelEncoder()
marital_statusint = marital_statusle.fit_transform(data["marital-status"])      

In [11]:
marital_statusint

array([4, 2, 0, ..., 6, 4, 2])

In [12]:
occupationle = LabelEncoder()
occupationint = occupationle.fit_transform(data.occupation)

In [13]:
occupationint

array([1, 4, 6, ..., 1, 1, 4])

In [14]:
relationshiple = LabelEncoder()
relationshipint = relationshiple.fit_transform(data.relationship)

In [15]:
relationshipint 

array([1, 0, 1, ..., 4, 3, 5])

In [16]:
racele = LabelEncoder()
raceint = racele.fit_transform(data.race)

In [17]:
raceint 

array([4, 4, 4, ..., 4, 4, 4])

In [18]:
sexle = LabelEncoder()
sexint = sexle.fit_transform(data.sex)

In [19]:
sexint

array([1, 1, 1, ..., 0, 1, 0])

In [20]:
native_countryle = LabelEncoder()
native_countryint = native_countryle.fit_transform(data["native-country"])

In [21]:
native_countryint

array([39, 39, 39, ..., 39, 39, 39])

In [22]:
incomele = LabelEncoder()
incomeint = incomele.fit_transform(data.income)

In [23]:
incomeint

array([0, 0, 0, ..., 0, 0, 1])

In [24]:
data["workClass_int"] = workClassle.transform(data.workClass) 
data["education_int"] = educationle.transform(data.education)
data["marital_status_int"] = marital_statusle.transform(data["marital-status"])
data["occupation_int"] = occupationle.transform(data.occupation)
data["relationship_int"] = relationshiple.transform(data.relationship)
data["race_int"] = racele.transform(data.race)
data["sex_int"] = sexle.transform(data.sex)
data["native_country_int"] = native_countryle.transform(data["native-country"])
data["income_int"] = incomele.transform(data.income)

In [25]:
data.head()

age          workClass  fnlwgt   education  education-num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   
3   53            Private  234721        11th              7   
4   28            Private  338409   Bachelors             13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   ...  income  workClass_int  education_int marital_status_int  \
0  ...   <=50K              7              9                  4   
1  ...   <=50K              6              9                  2   
2  ...   <=50K              4             11                  0   
3  ...   <=50K              4              1                  2   
4  ...   <=50K              4              9                  2   

  occupation_int  relationship_int  race_int  sex_int  native_country_int  \
0              1                 1         4        1                  39   
1              4                 0         4        1                  39   
2              6                 1         4        1                  39   
3              6                 0         2        1                  39   
4             10                 5         2        0                   5   

   income_int  
0           0  
1           0  
2           0  
3           0  
4           0  

[5 rows x 24 columns]

In [26]:
X = data[['age','workClass_int','fnlwgt','education_int','education-num','marital_status_int',
 'occupation_int','relationship_int','race_int','sex_int','capital-gain','capital-loss',
 'hours-per-week','native_country_int']].values
Y = data["income_int"].values

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2)

print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(26048, 14) (26048,)
(6513, 14) (6513,)


In [28]:
clf = LogisticRegression()
clf.fit(X_train,y_train)

G:\Anaconda\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [29]:
y_train_pred=clf.predict(X_train)

mse = mean_squared_error(y_train, y_train_pred)
mae = mean_absolute_error(y_train, y_train_pred)
r2 = r2_score(y_train, y_train_pred)

print("Train metrics: \nMean square error: ", mse, "\nMean absolute error: ", mae, "\nR2 score", r2)

Train metrics: 
Mean square error:  0.20185810810810811 
Mean absolute error:  0.20185810810810811 
R2 score -0.10831986915129477


In [30]:
y_train_pred = clf.predict(X_train)

acc = accuracy_score(y_train, y_train_pred)
print("Accuracy score: ", acc)

Accuracy score:  0.7981418918918919


In [31]:
y_test_pred=clf.predict(X_test)

mse = mean_squared_error(y_test, y_test_pred)
mae = mean_absolute_error(y_test, y_test_pred)
r2 = r2_score(y_test, y_test_pred)

print("Test metrics: \nMean square error: ", mse, "\nMean absolute error: ", mae, "\nR2 score", r2)

Test metrics: 
Mean square error:  0.21664363580531246 
Mean absolute error:  0.21664363580531246 
R2 score -0.16759728767217275


In [32]:
y_test_pred = clf.predict(X_test)

acc = accuracy_score(y_test, y_test_pred)
print("Accuracy score: ", acc)

Accuracy score:  0.7833563641946876


In [33]:
clf = SVC()
clf.fit(X_train,y_train)

G:\Anaconda\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [36]:
y_train_pred=clf.predict(X_train)

mse = mean_squared_error(y_train, y_train_pred)
mae = mean_absolute_error(y_train, y_train_pred)
r2 = r2_score(y_train, y_train_pred)
print("Train metrics: \nMean square error: ", mse, "\nMean absolute error: ", mae, "\nR2 score", r2)

Train metrics: 
Mean square error:  0.0010365479115479114 
Mean absolute error:  0.0010365479115479114 
R2 score 0.9943087416380592


In [37]:
y_test_pred=clf.predict(X_test)

mse = mean_squared_error(y_test, y_test_pred)
mae = mean_absolute_error(y_test, y_test_pred)
r2 = r2_score(y_test, y_test_pred)
print("Test metrics: \nMean square error: ", mse, "\nMean absolute error: ", mae, "\nR2 score", r2)

Test metrics: 
Mean square error:  0.24581606018731766 
Mean absolute error:  0.24581606018731766 
R2 score -0.32482158579953824
